import shutil
import argparse
from pathlib import Path
import random


# Path("abc.pred.xml").stem will yield "abc.pred".
# innermost_stem produces "abc" instead
def innermost_stem(path: Path) -> Path:
    path_stem = path.stem

    while path.suffixes:
        path = Path(path_stem)
        path_stem = path.stem

    return path_stem


def copy_gt(facsimile_path: Path, only_one: bool):
    training_path = Path("training")
    training_path.mkdir(exist_ok=True)

    for document_path in facsimile_path.iterdir():
        dta_dirname = innermost_stem(document_path)
        docs = list(document_path.iterdir())
        random.shuffle(docs)

        for doc_path in docs:
            if doc_path.suffixes == [".gt", ".xml"]:
                filename = f"{dta_dirname}_{innermost_stem(doc_path)}"

                img_path = (
                    document_path /
                    Path(f"{innermost_stem(doc_path)}.jpg")
                )
                if not img_path.is_file():
                    print(f"{img_path} is not a file, skipping...")
                    continue

                print(f"Copying {filename}...")
                shutil.copy(doc_path, training_path / f"{filename}.xml")
                shutil.copy(img_path, training_path / f"{filename}.jpg")

                if only_one:
                    break


def main():
    arg_parser = argparse.ArgumentParser(
        "copygt",
        description=(
            "Given a facsimile directory, copies the GT files and  " +
            "facsimiles into a training directory."
        )
    )
    arg_parser.add_argument(
        "--facsimile-dir", dest="facsimile_dir", default="facsimiles",
        help=(
            "The facsimile directory as generated by download.py " +
            "and segment.py."
        )
    )
    arg_parser.add_argument(
        "--only-one", dest="only_one", action="store_true",
        help="Copies only one random page from each work."
    )
    args = arg_parser.parse_args()

    facsimile_path = Path(args.facsimile_dir)
    if not facsimile_path.is_dir():
        print("Given --facsimile-dir is not a directory!!!")
        exit(1)

    copy_gt(facsimile_path, args.only_one)


if __name__ == "__main__":
    main()
