from typing import Iterable, Tuple
from pathlib import Path
import argparse


def segmentations(facsimile_path: Path) -> Iterable[Tuple[Path, Path]]:
    for doc_path in facsimile_path.iterdir():
        if doc_path.is_dir():
            bin_path = doc_path / "bin"
            if bin_path.is_dir():
                for seg_path in bin_path.iterdir():
                    if seg_path.is_file() and seg_path.name.endswith(".xml"):
                        yield seg_path, doc_path


def predict(facsimile_path: Path):
    pass


def main():
    arg_parser = argparse.ArgumentParser(
        "predict",
        description=(
            "Given a set of facsimiles with segmentations, in the same " +
            "format as the output of segment.py, Calamari is used to " +
            "predict the contents of the generated segmentations."
        )
    )
    arg_parser.add_argument(
        "--facsimile-dir", dest="facsimile_dir", default="facsimiles",
        help=(
            "The facsimile directory as generated by download.py " +
            " and segment.py."
        )
    )

    args = arg_parser.parse_args()
    facsimile_path = Path(args.facsimile_dir)
    predict(facsimile_path)


if __name__ == "__main__":
    main()
